services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app_network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

  api:
    build: .
    container_name: "api"
    networks:
      - app_network
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - 8000:8000

networks:
  app_network:
    driver: bridge